/**
 * This file was auto-generated by scripts/generate-openapi-types.ts.
 * Do not make direct changes to the file.
 */

export enum CommonStatus {
  /** 禁用 */
  DISABLED = 'DISABLED',
  /** 启用 */
  ENABLED = 'ENABLED',
}

/** 性别 */
export enum Gender {
  /** 男 */
  MALE = 'MALE',
  /** 女 */
  FEMALE = 'FEMALE',
  /** 未知 */
  UNKNOWN = 'UNKNOWN',
}

export enum OrganizationType {
  /** 公司 */
  COMPANY = 'COMPANY',
  /** 部门 */
  DEPARTMENT = 'DEPARTMENT',
}

export enum PermissionType {
  /** 目录 */
  DIRECTORY = 'DIRECTORY',
  /** 菜单 */
  MENU = 'MENU',
  /** 按钮 */
  BUTTON = 'BUTTON',
}

/** 用户状态 */
export enum UserStatus {
  /** 禁用 */
  DISABLED = 'DISABLED',
  /** 启用 */
  ENABLED = 'ENABLED',
}

export interface AccountLoginDto {
  /** @description 账号 */
  account: string
  /** @description 密码 */
  password: string
  /** @description 是否记住我 */
  rememberMe?: boolean
}

export interface DictItemSaveDto {
  /**
   * Format: int64
   * @description 字典 ID
   */
  dictId: number
  /** @description 字典项标签 */
  label: string
  /** @description 字典项编码 */
  value: string
  /**
   * @description 状态
   *      数据库默认值: 'ENABLED'
   * @enum {string}
   */
  status: CommonStatus
  /** @description 描述 */
  description?: string
  /**
   * Format: int32
   * @description 排序号
   */
  sortNum?: number
  /** @description 主题颜色 */
  themeColor?: string
  /** @description 主题类型 */
  themeType?: string
}

export interface DictItemSelfView {
  /**
   * Format: int64
   * @description 字典项 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 字典项标签 */
  label: string
  /** @description 字典项编码 */
  value: string
  /**
   * @description 状态
   *      数据库默认值: 'ENABLED'
   * @enum {string}
   */
  status: CommonStatus
  /** @description 描述 */
  description?: string
  /**
   * Format: int32
   * @description 排序号
   */
  sortNum?: number
  /** @description 主题颜色 */
  themeColor?: string
  /** @description 主题类型 */
  themeType?: string
  /** @description 字典编码 (核心业务键) */
  dictCode: string
}

export interface DictItemSpec {
  /**
   * Format: int64
   * @description 字典 ID
   */
  dictId: number
  /** @description 字典项标签 */
  label?: string
  /**
   * @description 状态
   *      数据库默认值: 'ENABLED'
   * @enum {string}
   */
  status?: CommonStatus
}

export interface DictSaveDto {
  /** @description 字典名称 */
  name: string
  /** @description 字典编码 (核心业务键) */
  code: string
  /**
   * @description 状态
   *      数据库默认值: 'ENABLED'
   * @enum {string}
   */
  status: CommonStatus
  /** @description 描述 */
  description?: string
}

export interface DictSelfView {
  /**
   * Format: int64
   * @description 字典 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 字典名称 */
  name: string
  /** @description 字典编码 (核心业务键) */
  code: string
  /**
   * @description 状态
   *      数据库默认值: 'ENABLED'
   * @enum {string}
   */
  status: CommonStatus
  /** @description 描述 */
  description?: string
}

export interface DictSpec {
  /** @description 字典名称 */
  name?: string
  /** @description 字典编码 (核心业务键) */
  code?: string
  /**
   * @description 状态
   *      数据库默认值: 'ENABLED'
   * @enum {string}
   */
  status?: CommonStatus
}

export interface DictView {
  /**
   * Format: int64
   * @description 字典 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 字典名称 */
  name: string
  /** @description 字典编码 (核心业务键) */
  code: string
  /**
   * @description 状态
   *      数据库默认值: 'ENABLED'
   * @enum {string}
   */
  status: CommonStatus
  /** @description 描述 */
  description?: string
  /** @description 字典项列表 */
  dictItems: TargetOf_dictItems[]
}

export interface EmailCodeLoginDto {
  /** @description 邮箱 */
  email: string
  /** @description 验证码 */
  code: string
  /** @description 是否记住登录 */
  rememberMe?: boolean
}

export interface EmailLoginDto {
  /** @description 邮箱 */
  email: string
  /** @description 密码 */
  password: string
  /** @description 是否记住登录 */
  rememberMe?: boolean
}

export interface OrganizationSaveDto {
  /** @description 组织名称 */
  name: string
  /**
   * @description 组织状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status: CommonStatus
  /**
   * @description 组织类型
   * @enum {string}
   */
  type: OrganizationType
  /**
   * Format: int64
   * @description 父组织 ID
   */
  parentId?: number
}

export interface OrganizationSelfView {
  /**
   * Format: int64
   * @description 组织 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 组织名称 */
  name: string
  /**
   * @description 组织状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status: CommonStatus
  /**
   * @description 组织类型
   * @enum {string}
   */
  type: OrganizationType
}

export interface OrganizationTreeView {
  /**
   * Format: int64
   * @description 组织 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 组织名称 */
  name: string
  /**
   * @description 组织状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status: CommonStatus
  /**
   * @description 组织类型
   * @enum {string}
   */
  type: OrganizationType
}

export interface OrganizationUserTreeView {
  /**
   * Format: int64
   * @description 组织 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 组织名称 */
  name: string
  /**
   * @description 组织状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status: CommonStatus
  /**
   * @description 组织类型
   * @enum {string}
   */
  type: OrganizationType
  /** @description 组织下的用户列表 */
  users: TargetOf_users[]
}

export interface OrganizationView {
  /**
   * Format: int64
   * @description 组织 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 组织名称 */
  name: string
  /**
   * @description 组织状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status: CommonStatus
  /**
   * @description 组织类型
   * @enum {string}
   */
  type: OrganizationType
  /** @description 父组织 */
  parent?: TargetOf_parent
}

export interface PageParam {
  /**
   * Format: int32
   * @description 当前页数,从 1 开始
   */
  page: number
  /**
   * Format: int32
   * @description 每页条数，默认值为 10
   */
  pageSize: number
}

export interface PageResultDictSelfView {
  /**
   * Format: int64
   * @description 数据总数
   */
  total?: number
  /**
   * Format: int64
   * @description 分页总数
   */
  pageTotal?: number
  /** @description 数据列表 */
  records?: DictSelfView[]
}

export interface PageResultRoleSelfView {
  /**
   * Format: int64
   * @description 数据总数
   */
  total?: number
  /**
   * Format: int64
   * @description 分页总数
   */
  pageTotal?: number
  /** @description 数据列表 */
  records?: RoleSelfView[]
}

export interface PageResultUserSelfView {
  /**
   * Format: int64
   * @description 数据总数
   */
  total?: number
  /**
   * Format: int64
   * @description 分页总数
   */
  pageTotal?: number
  /** @description 数据列表 */
  records?: UserSelfView[]
}

export interface PermissionSaveDto {
  /** @description 菜单名称 */
  name: string
  /**
   * Format: int64
   * @description 父菜单 ID
   */
  parentId?: number
  /**
   * @description 类型（DIRECTORY:目录 MENU:菜单 BUTTON:按钮）
   * @enum {string}
   */
  type: PermissionType
  /** @description 路由地址 或 外链地址,仅对目录和菜单有效 */
  path?: string
  /** @description 路径参数,仅对菜单有效 */
  pathParams?: string
  /** @description 权限标识，仅对按钮有效 */
  permission?: string
  /** @description 图标,仅对目录和菜单有效 */
  icon?: string
  /** @description 固定标签栏上，仅对菜单有效 */
  affixTab?: boolean
  /** @description 忽略权限，没有权限或者未登录的时候可以直接访问该页面，仅对菜单有效 */
  ignoreAuth?: boolean
  /** @description 是否缓存菜单，仅对菜单有效 */
  keepAlive?: boolean
  /** @description 内嵌地址，仅对菜单有效 */
  iframeSrc?: string
  /** @description 是否自定义内嵌组件，仅对菜单有效且 iframeSrc 不为空 */
  customizeIframeComponent?: boolean
  /** @description 隐藏菜单，但是可以通过路由访问 */
  hideMenu?: boolean
  /** @description 禁用菜单，不能通过路由访问 */
  disabledMenu?: boolean
  /**
   * Format: int32
   * @description 排序
   */
  sortNum?: number
}

export interface PermissionSelfView {
  /**
   * Format: int64
   * @description 权限 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 菜单名称 */
  name: string
  /**
   * @description 类型（DIRECTORY:目录 MENU:菜单 BUTTON:按钮）
   * @enum {string}
   */
  type: PermissionType
  /** @description 路由地址 或 外链地址,仅对目录和菜单有效 */
  path?: string
  /** @description 路径参数,仅对菜单有效 */
  pathParams?: string
  /** @description 权限标识，仅对按钮有效 */
  permission?: string
  /** @description 图标,仅对目录和菜单有效 */
  icon?: string
  /** @description 固定标签栏上，仅对菜单有效 */
  affixTab?: boolean
  /** @description 忽略权限，没有权限或者未登录的时候可以直接访问该页面，仅对菜单有效 */
  ignoreAuth?: boolean
  /** @description 是否缓存菜单，仅对菜单有效 */
  keepAlive?: boolean
  /** @description 内嵌地址，仅对菜单有效 */
  iframeSrc?: string
  /** @description 是否自定义内嵌组件，仅对菜单有效且 iframeSrc 不为空 */
  customizeIframeComponent?: boolean
  /** @description 隐藏菜单，但是可以通过路由访问 */
  hideMenu?: boolean
  /** @description 禁用菜单，不能通过路由访问 */
  disabledMenu?: boolean
  /** @description 是否为根页面（首页入口） */
  rootPage?: boolean
  /**
   * Format: int32
   * @description 排序
   */
  sortNum?: number
  /**
   * Format: int64
   * @description 父菜单 ID
   */
  parentId?: number
}

export interface PermissionTreeView {
  /**
   * Format: int64
   * @description 权限 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 菜单名称 */
  name: string
  /**
   * @description 类型（DIRECTORY:目录 MENU:菜单 BUTTON:按钮）
   * @enum {string}
   */
  type: PermissionType
  /** @description 路由地址 或 外链地址,仅对目录和菜单有效 */
  path?: string
  /** @description 路径参数,仅对菜单有效 */
  pathParams?: string
  /** @description 权限标识，仅对按钮有效 */
  permission?: string
  /** @description 图标,仅对目录和菜单有效 */
  icon?: string
  /** @description 固定标签栏上，仅对菜单有效 */
  affixTab?: boolean
  /** @description 忽略权限，没有权限或者未登录的时候可以直接访问该页面，仅对菜单有效 */
  ignoreAuth?: boolean
  /** @description 是否缓存菜单，仅对菜单有效 */
  keepAlive?: boolean
  /** @description 内嵌地址，仅对菜单有效 */
  iframeSrc?: string
  /** @description 是否自定义内嵌组件，仅对菜单有效且 iframeSrc 不为空 */
  customizeIframeComponent?: boolean
  /** @description 隐藏菜单，但是可以通过路由访问 */
  hideMenu?: boolean
  /** @description 禁用菜单，不能通过路由访问 */
  disabledMenu?: boolean
  /**
   * Format: int32
   * @description 排序
   */
  sortNum?: number
}

export interface PermissionView {
  /**
   * Format: int64
   * @description 权限 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 菜单名称 */
  name: string
  /**
   * @description 类型（DIRECTORY:目录 MENU:菜单 BUTTON:按钮）
   * @enum {string}
   */
  type: PermissionType
  /** @description 路由地址 或 外链地址,仅对目录和菜单有效 */
  path?: string
  /** @description 路径参数,仅对菜单有效 */
  pathParams?: string
  /** @description 权限标识，仅对按钮有效 */
  permission?: string
  /** @description 图标,仅对目录和菜单有效 */
  icon?: string
  /** @description 固定标签栏上，仅对菜单有效 */
  affixTab?: boolean
  /** @description 忽略权限，没有权限或者未登录的时候可以直接访问该页面，仅对菜单有效 */
  ignoreAuth?: boolean
  /** @description 是否缓存菜单，仅对菜单有效 */
  keepAlive?: boolean
  /** @description 内嵌地址，仅对菜单有效 */
  iframeSrc?: string
  /** @description 是否自定义内嵌组件，仅对菜单有效且 iframeSrc 不为空 */
  customizeIframeComponent?: boolean
  /** @description 隐藏菜单，但是可以通过路由访问 */
  hideMenu?: boolean
  /** @description 禁用菜单，不能通过路由访问 */
  disabledMenu?: boolean
  /**
   * Format: int32
   * @description 排序
   */
  sortNum?: number
  /**
   * Format: int64
   * @description 父菜单 ID
   */
  parentId?: number
  /** @description 父权限 */
  parent?: TargetOf_parent
}

export interface RoleAssignUsersDto {
  /** @description 用户ID列表 */
  userIds: number[]
}

export interface RoleSaveDto {
  /** @description 角色名称 */
  name: string
  /** @description 角色标识 */
  code: string
  /**
   * @description 角色状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status: CommonStatus
  /** @description 描述 */
  description?: string
  /** @description 权限列表 */
  permissionIds?: number[]
}

export interface RoleSelfView {
  /**
   * Format: int64
   * @description 角色 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 角色名称 */
  name: string
  /** @description 角色标识 */
  code: string
  /**
   * @description 角色状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status: CommonStatus
  /** @description 描述 */
  description?: string
}

export interface RoleSpec {
  /** @description 角色名称 */
  name?: string
  /** @description 角色标识 */
  code?: string
  /**
   * @description 角色状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status?: CommonStatus
}

export interface RoleView {
  /**
   * Format: int64
   * @description 角色 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 角色名称 */
  name: string
  /** @description 角色标识 */
  code: string
  /**
   * @description 角色状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status: CommonStatus
  /** @description 描述 */
  description?: string
  /** @description 权限列表 */
  permissions: TargetOf_permissions[]
}

export interface SendEmailLoginCodeDto {
  /** @description 邮箱 */
  email: string
}

export interface TargetOf_dictItems {
  /**
   * Format: int64
   * @description 字典项 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 字典项标签 */
  label: string
  /** @description 字典项编码 */
  value: string
  /**
   * @description 状态
   *      数据库默认值: 'ENABLED'
   * @enum {string}
   */
  status: CommonStatus
  /** @description 描述 */
  description?: string
  /**
   * Format: int32
   * @description 排序号
   */
  sortNum?: number
  /** @description 主题颜色 */
  themeColor?: string
  /** @description 主题类型 */
  themeType?: string
}

export interface TargetOf_parent {
  /**
   * Format: int64
   * @description 权限 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 菜单名称 */
  name: string
  /**
   * @description 类型（DIRECTORY:目录 MENU:菜单 BUTTON:按钮）
   * @enum {string}
   */
  type: PermissionType
  /** @description 路由地址 或 外链地址,仅对目录和菜单有效 */
  path?: string
  /** @description 路径参数,仅对菜单有效 */
  pathParams?: string
  /** @description 权限标识，仅对按钮有效 */
  permission?: string
  /** @description 图标,仅对目录和菜单有效 */
  icon?: string
  /** @description 固定标签栏上，仅对菜单有效 */
  affixTab?: boolean
  /** @description 忽略权限，没有权限或者未登录的时候可以直接访问该页面，仅对菜单有效 */
  ignoreAuth?: boolean
  /** @description 是否缓存菜单，仅对菜单有效 */
  keepAlive?: boolean
  /** @description 内嵌地址，仅对菜单有效 */
  iframeSrc?: string
  /** @description 是否自定义内嵌组件，仅对菜单有效且 iframeSrc 不为空 */
  customizeIframeComponent?: boolean
  /** @description 隐藏菜单，但是可以通过路由访问 */
  hideMenu?: boolean
  /** @description 禁用菜单，不能通过路由访问 */
  disabledMenu?: boolean
  /**
   * Format: int32
   * @description 排序
   */
  sortNum?: number
}

export interface TargetOf_permissions {
  /**
   * Format: int64
   * @description 权限 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 菜单名称 */
  name: string
  /**
   * @description 类型（DIRECTORY:目录 MENU:菜单 BUTTON:按钮）
   * @enum {string}
   */
  type: PermissionType
  /** @description 路由地址 或 外链地址,仅对目录和菜单有效 */
  path?: string
  /** @description 路径参数,仅对菜单有效 */
  pathParams?: string
  /** @description 权限标识，仅对按钮有效 */
  permission?: string
  /** @description 图标,仅对目录和菜单有效 */
  icon?: string
  /** @description 固定标签栏上，仅对菜单有效 */
  affixTab?: boolean
  /** @description 忽略权限，没有权限或者未登录的时候可以直接访问该页面，仅对菜单有效 */
  ignoreAuth?: boolean
  /** @description 是否缓存菜单，仅对菜单有效 */
  keepAlive?: boolean
  /** @description 内嵌地址，仅对菜单有效 */
  iframeSrc?: string
  /** @description 是否自定义内嵌组件，仅对菜单有效且 iframeSrc 不为空 */
  customizeIframeComponent?: boolean
  /** @description 隐藏菜单，但是可以通过路由访问 */
  hideMenu?: boolean
  /** @description 禁用菜单，不能通过路由访问 */
  disabledMenu?: boolean
  /**
   * Format: int32
   * @description 排序
   */
  sortNum?: number
}

export interface TargetOf_roles {
  /**
   * Format: int64
   * @description 角色 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 角色名称 */
  name: string
  /** @description 角色标识 */
  code: string
  /**
   * @description 角色状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status: CommonStatus
  /** @description 描述 */
  description?: string
}

export interface TargetOf_users {
  /**
   * Format: int64
   * @description 用户 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 账号 */
  account: string
  /** @description 邮箱 */
  email?: string
  /** @description 手机号 */
  phoneNumber?: string
  /**
   * @description 用户状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status: UserStatus
  /** @description 昵称 */
  nickname: string
  /** @description 头像 */
  avatar?: string
  /**
   * @description 性别（MALE:男 FEMALE:女 UNKNOWN:未知），默认 UNKNOWN
   * @enum {string}
   */
  gender?: Gender
}

export interface UpdatePasswordDto {
  /** @description 旧密码 */
  oldPassword: string
  /** @description 新密码 */
  newPassword: string
}

export interface UserAssignRolesDto {
  /** @description 角色 ID 列表 */
  roleIds: number[]
}

export interface UserProfileView {
  /** @description 用户信息 */
  user: UserView
  /** @description 细粒度权限 */
  permissions: string[]
  /** @description 菜单列表 */
  menus: PermissionSelfView[]
  /** @description 角色列表 */
  roles: RoleSelfView[]
}

export interface UserSaveDto {
  /** @description 账号 */
  account: string
  /** @description 邮箱 */
  email?: string
  /** @description 手机号 */
  phoneNumber?: string
  /** @description 密码 */
  password: string
  /**
   * @description 性别（MALE:男 FEMALE:女 UNKNOWN:未知），默认 UNKNOWN
   * @enum {string}
   */
  gender?: Gender
  /** @description 头像 */
  avatar?: string
  /**
   * @description 用户状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status: UserStatus
  /** @description 昵称 */
  nickname: string
  /** @description 角色 ID 列表 */
  roleIds?: number[]
  /**
   * Format: int64
   * @description 组织 ID
   */
  organizationId: number
}

export interface UserSelfView {
  /**
   * Format: int64
   * @description 用户 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 账号 */
  account: string
  /** @description 邮箱 */
  email?: string
  /** @description 手机号 */
  phoneNumber?: string
  /**
   * @description 用户状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status: UserStatus
  /** @description 昵称 */
  nickname: string
  /** @description 头像 */
  avatar?: string
  /**
   * @description 性别（MALE:男 FEMALE:女 UNKNOWN:未知），默认 UNKNOWN
   * @enum {string}
   */
  gender?: Gender
  /** @description 性别名称 */
  genderName?: string
  /** @description 状态名称 */
  statusName?: string
  /** @description 创建人名称 */
  createByName?: string
}

export interface UserSpec {
  /**
   * Format: int64
   * @description 组织 ID
   */
  organizationId?: number
  /** @description 账号 */
  account?: string
  /** @description 邮箱 */
  email?: string
  /** @description 手机号 */
  phoneNumber?: string
  /**
   * @description 用户状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status?: UserStatus
  /**
   * @description 性别（MALE:男 FEMALE:女 UNKNOWN:未知），默认 UNKNOWN
   * @enum {string}
   */
  gender?: Gender
  /** @description 昵称 */
  nickname?: string
}

export interface UserUpdateProfileDto {
  /** @description 昵称 */
  nickname: string
  /** @description 头像 */
  avatar?: string
  /**
   * @description 性别（MALE:男 FEMALE:女 UNKNOWN:未知），默认 UNKNOWN
   * @enum {string}
   */
  gender?: Gender
}

export interface UserUpdateStatusDto {
  /**
   * @description 用户状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status: UserStatus
}

export interface UserView {
  /**
   * Format: int64
   * @description 用户 ID
   */
  id: number
  /**
   * Format: int64
   * @description 创建者
   */
  createBy?: number
  /**
   * Format: date-time
   * @description 创建时间
   */
  createTime?: string
  /**
   * Format: int64
   * @description 更新者
   */
  updateBy?: number
  /**
   * Format: date-time
   * @description 更新时间
   */
  updateTime?: string
  /** @description 账号 */
  account: string
  /** @description 邮箱 */
  email?: string
  /** @description 手机号 */
  phoneNumber?: string
  /**
   * @description 用户状态（ENABLED:启用 DISABLED:停用）,默认 ENABLED
   * @enum {string}
   */
  status: UserStatus
  /** @description 昵称 */
  nickname: string
  /** @description 头像 */
  avatar?: string
  /**
   * @description 性别（MALE:男 FEMALE:女 UNKNOWN:未知），默认 UNKNOWN
   * @enum {string}
   */
  gender?: Gender
  /** @description 角色列表 */
  roles: TargetOf_roles[]
  /** @description 性别名称 */
  genderName?: string
  /** @description 状态名称 */
  statusName?: string
  /** @description 创建人名称 */
  createByName?: string
}

export type ApiPath
  /** 账号密码登录 */
  = | '/auth/login/account'
  /** 邮箱登录 */
    | '/auth/login/email'
  /** 邮箱验证码登录 */
    | '/auth/login/email/code'
  /** 发送邮箱登录验证码 */
    | '/auth/login/email/code/send'
  /** 登出 */
    | '/auth/logout'
  /** 修改个人信息 */
    | '/profile'
  /** 获取当前用户信息 */
    | '/profile/me'
  /** 修改密码 */
    | '/profile/password'
  /** 获取字典项列表、创建字典项 */
    | '/system/dict-item/'
  /** 更新字典项、删除字典项 */
    | '/system/dict-item/{id}'
  /** 根据字典代码获取字典项列表 */
    | '/system/dict-item/code/{code}'
  /** 批量获取字典项 (按编码分组) */
    | '/system/dict-item/grouped'
  /** 获取全部字典、创建字典 */
    | '/system/dict/'
  /** 获取字典详情、更新字典、删除字典 */
    | '/system/dict/{id}'
  /** 获取字典分页列表 */
    | '/system/dict/page'
  /** 获取全部组织、创建组织 */
    | '/system/organization/'
  /** 获取组织详情、更新组织、删除组织 */
    | '/system/organization/{id}'
  /** 获取组织树 */
    | '/system/organization/tree'
  /** 获取带用户的组织树 */
    | '/system/organization/user-tree'
  /** 获取权限列表、创建权限 */
    | '/system/permission/'
  /** 获取权限详情、更新权限、删除权限 */
    | '/system/permission/{id}'
  /** 获取权限树 */
    | '/system/permission/tree'
  /** 获取全部角色、创建角色 */
    | '/system/role/'
  /** 获取角色详情、更新角色、删除角色 */
    | '/system/role/{id}'
  /** 分配用户 */
    | '/system/role/{id}/users'
  /** 获取角色分页列表 */
    | '/system/role/page'
  /** 获取全部用户、创建用户 */
    | '/system/user/'
  /** 获取用户详情、更新用户、删除用户 */
    | '/system/user/{id}'
  /** 获取用户按钮权限列表 */
    | '/system/user/{id}/button-permissions'
  /** 获取用户角色 code 列表 */
    | '/system/user/{id}/role-codes'
  /** 分配角色 */
    | '/system/user/{id}/roles'
  /** 更新用户状态 */
    | '/system/user/{id}/status'
  /** 获取用户分页列表 */
    | '/system/user/page'
