#!/usr/bin/env node
import type { OpenAPI3 } from 'openapi-typescript'
import { execSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import * as process from 'node:process'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'
import ts from 'typescript'

const LINE_BREAK_RE = /\r?\n/
const INLINE_COMMENT_RE = /\s+#.*$/
// 匹配响应包装类型名（如 RVoid、RPageResultXxx），这些由请求层统一处理，不需要导出为实体类型
const RESPONSE_WRAPPER_NAME_RE = /^R[A-Z]/
const VALID_TYPE_NAME_RE = /^[A-Z_]\w*$/i
const SCHEMA_REF_RE = /components\["schemas"\]\["([^"]+)"\]/g

const GENERATED_FILE_HEADER = `/**
 * This file was auto-generated by scripts/generate-openapi-types.ts.
 * Do not make direct changes to the file.
 */`

const DEFAULT_OUTPUT = 'types/openapi-types.ts'
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const rawArgs = process.argv.slice(2)

const modeIndex = rawArgs.findIndex(arg => arg === '--mode')
const modeFromEquals = rawArgs.find(arg => arg.startsWith('--mode='))?.slice('--mode='.length)
const modeFromNext = modeIndex >= 0 ? rawArgs[modeIndex + 1] : undefined
const mode = process.env.MODE || modeFromEquals || modeFromNext || 'development'
const dryRun = rawArgs.includes('--dry-run')

function parseEnvFile(filePath: string): Record<string, string> {
  if (!existsSync(filePath)) {
    return {}
  }

  return readFileSync(filePath, 'utf8')
    .split(LINE_BREAK_RE)
    .reduce<Record<string, string>>((env, line) => {
      const text = line.trim()
      if (!text || text.startsWith('#')) {
        return env
      }

      const equalIndex = text.indexOf('=')
      if (equalIndex < 0) {
        return env
      }

      const key = text.slice(0, equalIndex).trim()
      let value = text.slice(equalIndex + 1).trim()
      const quote = value[0]

      if ((quote === '"' || quote === '\'' || quote === '`') && value.at(-1) === quote) {
        value = value.slice(1, -1)
      }
      else {
        value = value.replace(INLINE_COMMENT_RE, '')
      }

      env[key] = value
      return env
    }, {})
}

function isHttpUrl(value: string): boolean {
  try {
    const url = new URL(value)
    return url.protocol === 'http:' || url.protocol === 'https:'
  }
  catch {
    return false
  }
}

function isObject(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object'
}

function validateOpenapiDocument(doc: unknown): asserts doc is OpenAPI3 {
  if (!isObject(doc)) {
    throw new Error('OpenAPI 文档格式无效：期望 JSON 对象。')
  }
  if (typeof doc.openapi !== 'string') {
    throw new TypeError('OpenAPI 文档格式无效：缺少 "openapi" 版本字段。')
  }
  if (!doc.openapi.startsWith('3.')) {
    throw new Error(`不支持的 OpenAPI 版本：${doc.openapi}，仅支持 3.x。`)
  }
  if (!isObject(doc.info) || typeof doc.info.title !== 'string') {
    throw new Error('OpenAPI 文档格式无效：缺少 "info.title" 字段。')
  }
}

async function loadOpenapiDocument(input: string, env: Record<string, string>): Promise<unknown> {
  // 检查是否是 HTTP URL（但格式可能错误）
  if (input.startsWith('http:') || input.startsWith('https:')) {
    if (!input.startsWith('http://') && !input.startsWith('https://')) {
      throw new Error(`URL 格式错误：${input}\n\n正确格式应该是：\n- http://localhost:8080/v3/api-docs\n- https://example.com/v3/api-docs\n\n注意：http: 后面需要两个斜杠 //`)
    }
  }

  if (!isHttpUrl(input)) {
    try {
      return JSON.parse(readFileSync(resolve(root, input), 'utf8'))
    }
    catch (err) {
      if (err instanceof Error && err.message.includes('ENOENT')) {
        throw new Error(`找不到本地 OpenAPI 文档文件：${input}\n\n请检查：\n1. 文件路径是否正确\n2. 如果是 URL，请确保格式正确（http:// 或 https://）`)
      }
      throw new Error(`读取本地 OpenAPI 文档失败：${input}\n${err instanceof Error ? err.message : String(err)}`)
    }
  }

  try {
    // 从环境变量读取认证信息
    const authToken = env.OPENAPI_AUTH_TOKEN
    const authUser = env.OPENAPI_AUTH_USER
    const authPass = env.OPENAPI_AUTH_PASS

    const headers: Record<string, string> = {}

    // 支持 Bearer Token 认证
    if (authToken) {
      headers.Authorization = `Bearer ${authToken}`
    }
    // 支持 Basic Auth 认证
    else if (authUser && authPass) {
      const credentials = Buffer.from(`${authUser}:${authPass}`).toString('base64')
      headers.Authorization = `Basic ${credentials}`
    }

    const response = await fetch(input, { headers })
    if (!response.ok) {
      if (response.status === 401 || response.status === 403) {
        throw new Error(`请求 OpenAPI 文档失败：${response.status} ${response.statusText}\nURL: ${input}\n\n认证失败，请检查：\n1. 后端是否需要认证访问 API 文档\n2. 如需认证，请在 .env 文件中配置：\n   - Bearer Token: OPENAPI_AUTH_TOKEN=your-token\n   - Basic Auth: OPENAPI_AUTH_USER=username 和 OPENAPI_AUTH_PASS=password`)
      }
      throw new Error(`请求 OpenAPI 文档失败：${response.status} ${response.statusText}\nURL: ${input}\n\n请检查：\n1. 后端服务是否正常运行\n2. URL 配置是否正确（检查 .env 文件中的 VITE_OPENAPI_URL）\n3. 网络连接是否正常`)
    }

    const contentType = response.headers.get('content-type')
    if (contentType && !contentType.includes('application/json')) {
      throw new Error(`OpenAPI 文档返回了非 JSON 格式：${contentType}\nURL: ${input}\n\n可能原因：\n1. URL 指向了错误的端点（应该指向 /v3/api-docs）\n2. 后端服务返回了错误页面`)
    }

    return await response.json()
  }
  catch (err) {
    if (err instanceof Error && err.message.includes('fetch failed')) {
      throw new Error(`无法连接到后端服务：${input}\n\n请检查：\n1. 后端服务是否正常运行\n2. URL 是否正确（检查 .env 文件中的 VITE_OPENAPI_URL）\n3. 端口号是否正确\n4. 是否有防火墙或代理阻止连接`)
    }
    throw err
  }
}

function getPropertyName(name: ts.PropertyName | undefined): string | undefined {
  if (!name) {
    return undefined
  }
  if (ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name)) {
    return name.text
  }
  return undefined
}

function getDeclarationMembers(declaration: ts.Declaration): readonly ts.TypeElement[] {
  if (ts.isInterfaceDeclaration(declaration)) {
    return declaration.members
  }
  if (ts.isTypeAliasDeclaration(declaration) && ts.isTypeLiteralNode(declaration.type)) {
    return declaration.type.members
  }
  return []
}
function findDeclaration(sourceFile: ts.SourceFile, name: string): ts.InterfaceDeclaration | ts.TypeAliasDeclaration | undefined {
  return sourceFile.statements.find((node): node is ts.InterfaceDeclaration | ts.TypeAliasDeclaration => {
    if (!ts.isInterfaceDeclaration(node) && !ts.isTypeAliasDeclaration(node)) {
      return false
    }
    return node.name.text === name
  })
}

function replaceSchemaRefs(typeText: string): string {
  return typeText.replace(SCHEMA_REF_RE, (_, schemaName: string) => {
    if (RESPONSE_WRAPPER_NAME_RE.test(schemaName) || !VALID_TYPE_NAME_RE.test(schemaName)) {
      return 'unknown'
    }
    return schemaName
  })
}

function createEntityTypes(source: string, enumFieldMap: Map<string, Map<string, string>>): string[] {
  const sourceFile = ts.createSourceFile('openapi.d.ts', source, ts.ScriptTarget.Latest, true)
  const componentsDeclaration = findDeclaration(sourceFile, 'components')

  if (!componentsDeclaration) {
    console.warn('openapi-typescript 输出中未找到 components 类型，跳过实体类型生成。')
    return []
  }

  const schemasProperty = getDeclarationMembers(componentsDeclaration)
    .find(member => ts.isPropertySignature(member) && getPropertyName(member.name) === 'schemas')

  if (!schemasProperty || !ts.isPropertySignature(schemasProperty) || !schemasProperty.type || !ts.isTypeLiteralNode(schemasProperty.type)) {
    return []
  }

  return schemasProperty.type.members
    .filter((member): member is ts.PropertySignature => ts.isPropertySignature(member) && Boolean(member.type))
    .map((member) => {
      const schemaName = getPropertyName(member.name)
      if (!schemaName || RESPONSE_WRAPPER_NAME_RE.test(schemaName) || !VALID_TYPE_NAME_RE.test(schemaName)) {
        return undefined
      }
      let typeText = replaceSchemaRefs(member.type!.getText(sourceFile))
      typeText = replaceEnumFields(typeText, schemaName, enumFieldMap)
      return `export type ${schemaName} = ${typeText}`
    })
    .filter((item): item is string => item !== undefined)
    .sort((typeA, typeB) => typeA.localeCompare(typeB))
}

function replaceEnumFields(typeText: string, schemaName: string, enumFieldMap: Map<string, Map<string, string>>): string {
  const fieldMap = enumFieldMap.get(schemaName)
  if (!fieldMap)
    return typeText

  for (const [fieldName, enumName] of fieldMap) {
    // 匹配字段定义中的枚举字面量联合，如: fieldName?: "A" | "B" 或 fieldName: "A" | "B"
    const fieldPattern = new RegExp(`(${fieldName}\\??: )("[^"]*"(?:\\s*\\|\\s*"[^"]*")*)`, 'g')
    typeText = typeText.replace(fieldPattern, `$1${enumName}`)
  }
  return typeText
}

function getPathSummaries(pathItem: unknown): string {
  if (!isObject(pathItem))
    return ''
  const methods = ['get', 'post', 'put', 'delete', 'patch']
  const summaries = methods
    .filter(m => isObject(pathItem[m]) && typeof (pathItem[m] as Record<string, unknown>).summary === 'string')
    .map(m => (pathItem[m] as Record<string, unknown>).summary as string)
  return summaries.join('、')
}

function createPathUnion(openapiDocument: OpenAPI3): string {
  const pathEntries = Object.entries(openapiDocument.paths ?? {})
    .sort(([a], [b]) => a.localeCompare(b))

  const paths = pathEntries.map(([apiPath, pathItem]) => {
    const summaries = getPathSummaries(pathItem)
    const comment = summaries ? `  /** ${summaries} */\n` : ''
    return `${comment}  | ${JSON.stringify(apiPath)}`
  })

  return paths.length > 0
    ? `export type ApiPath =\n${paths.join('\n')}`
    : 'export type ApiPath = never'
}

interface EnumInfo {
  values: (string | number)[]
  varnames: string[]
  description?: string
  valueDescriptions?: string[]
}

function collectEnumTypes(openapiDocument: OpenAPI3): Map<string, EnumInfo> {
  const enums = new Map<string, EnumInfo>()
  const schemas = (openapiDocument.components as Record<string, unknown>)?.schemas

  if (!isObject(schemas))
    return enums

  for (const schema of Object.values(schemas)) {
    if (!isObject(schema))
      continue
    const properties = schema.properties
    if (!isObject(properties))
      continue

    for (const prop of Object.values(properties)) {
      if (!isObject(prop))
        continue
      const enumName = prop['x-enum-name']
      const enumValues = prop.enum
      if (typeof enumName === 'string' && Array.isArray(enumValues) && !enums.has(enumName)) {
        const varnames = Array.isArray(prop['x-enum-varnames'])
          ? prop['x-enum-varnames'] as string[]
          : enumValues.map(String)
        const description = typeof prop['x-enum-description'] === 'string' ? prop['x-enum-description'] : undefined
        const valueDescriptions = Array.isArray(prop['x-enum-value-descriptions'])
          ? prop['x-enum-value-descriptions'] as string[]
          : undefined
        enums.set(enumName, { values: enumValues as (string | number)[], varnames, description, valueDescriptions })
      }
    }
  }

  return enums
}

function buildEnumFieldMap(openapiDocument: OpenAPI3): Map<string, Map<string, string>> {
  const result = new Map<string, Map<string, string>>()
  const schemas = (openapiDocument.components as Record<string, unknown>)?.schemas

  if (!isObject(schemas))
    return result

  for (const [schemaName, schema] of Object.entries(schemas)) {
    if (!isObject(schema))
      continue
    const properties = schema.properties
    if (!isObject(properties))
      continue

    for (const [propName, prop] of Object.entries(properties)) {
      if (!isObject(prop))
        continue
      const enumName = prop['x-enum-name']
      if (typeof enumName !== 'string')
        continue

      if (!result.has(schemaName)) {
        result.set(schemaName, new Map())
      }
      result.get(schemaName)!.set(propName, enumName)
    }
  }

  return result
}

function createEnumTypes(enums: Map<string, EnumInfo>): string[] {
  return Array.from(enums.entries())
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, { values, varnames, description, valueDescriptions }]) => {
      const lines: string[] = []
      if (description) {
        lines.push(`/** ${description} */`)
      }
      lines.push(`export enum ${name} {`)
      varnames.forEach((varname, i) => {
        const valueDesc = valueDescriptions?.[i]
        if (valueDesc) {
          lines.push(`  /** ${valueDesc} */`)
        }
        const value = values[i]
        const formatted = typeof value === 'number' ? String(value) : `'${value}'`
        lines.push(`  ${varname} = ${formatted},`)
      })
      lines.push('}')
      return lines.join('\n')
    })
}

function createOutputContent(openapiDocument: OpenAPI3, entityTypes: string[], enumTypes: string[]): string {
  return [
    GENERATED_FILE_HEADER,
    ...enumTypes,
    ...entityTypes,
    createPathUnion(openapiDocument),
    '',
  ].join('\n\n')
}

async function generate(): Promise<void> {
  const loadedEnv = ['.env', '.env.local', `.env.${mode}`, `.env.${mode}.local`]
    .map(fileName => resolve(root, fileName))
    .reduce<Record<string, string>>((env, filePath) => ({ ...env, ...parseEnvFile(filePath) }), {})

  const env = { ...loadedEnv, ...process.env }
  const openapiUrl = env.VITE_OPENAPI_URL
  const outputFile = env.OPENAPI_TYPES_OUTPUT || DEFAULT_OUTPUT
  const outputPath = resolve(root, outputFile)

  if (!openapiUrl) {
    console.error(`缺少 VITE_OPENAPI_URL，请在 .env 或 .env.${mode} 中配置 OpenAPI 地址。`)
    process.exit(1)
  }

  if (dryRun) {
    console.log(`mode:   ${mode}`)
    console.log(`input:  ${openapiUrl}`)
    console.log(`output: ${outputPath}`)
    process.exit(0)
  }

  const rawDocument = await loadOpenapiDocument(openapiUrl, env)
  validateOpenapiDocument(rawDocument)

  const enums = collectEnumTypes(rawDocument)
  const enumFieldMap = buildEnumFieldMap(rawDocument)
  const enumTypes = createEnumTypes(enums)
  const fullTypes = astToString(await openapiTS(rawDocument))
  const entityTypes = createEntityTypes(fullTypes, enumFieldMap)
  const output = createOutputContent(rawDocument, entityTypes, enumTypes)

  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, output)
  try {
    execSync(`npx eslint --fix ${outputPath}`, { stdio: 'inherit', cwd: root })
  }
  catch {
    // eslint fix 失败不影响生成
  }
  console.log(`OpenAPI 类型已生成：${outputPath}`)
}

generate().catch((err) => {
  console.error(err instanceof Error ? err.message : err)
  process.exit(1)
})
