import {
  NAutoComplete,
  NCascader,
  NCheckbox,
  NCheckboxGroup,
  NColorPicker,
  NDatePicker,
  NDynamicInput,
  NDynamicTags,
  NInput,
  NInputNumber,
  NMention,
  NRadio,
  NRadioGroup,
  NRate,
  NSelect,
  NSlider,
  NSwitch,
  NTimePicker,
  NTransfer,
  NTreeSelect,
  NUpload,
} from 'naive-ui'
import IconSelector from '@/components/common/icon/icon-selector.vue'
// schema form 可渲染的组件
export const SCHEMA_RENDER_COMPONENTS = {
  input: NInput,
  select: NSelect,
  autoComplete: NAutoComplete,
  cascader: NCascader,
  colorPicker: NColorPicker,
  checkbox: NCheckbox,
  checkboxGroup: NCheckboxGroup,
  datePicker: NDatePicker,
  dynamicInput: NDynamicInput,
  dynamicTags: NDynamicTags,
  inputNumber: NInputNumber,
  mention: NMention,
  radio: NRadio,
  radioGroup: NRadioGroup,
  rate: NRate,
  slider: NSlider,
  switch: NSwitch,
  timePicker: NTimePicker,
  transfer: NTransfer,
  treeSelect: NTreeSelect,
  upload: NUpload,
  iconSelect: IconSelector,
}
